version: "3.3"
services:
  app:
    build:
      context: .
    environment:
      MAX_REQUEST: "30"
      TOKEN_BUCKET_RATE_PER_SECOND: "1"
    ports:
      - '8080:8080'
    volumes:
      - ./logs/:/logs/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.0
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 5044:5044
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - 5601:5601